# Site settings
title: Alan Monger
email: alan@alanmonger.co.uk
description: > # this means to ignore newlines until "baseurl:"
    A tech blog with things I find interesting
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: haveacigaro
github_username: amonger

# Build settings
markdown: kramdown
